config/routes.rb
Rails.application.routes.draw do
  resources :issue_comments
  resources :work_entries
  resources :users
  resources :teams

  resources :sprints do
    resources :issues
  end
  resources :projects do
    resources :issues
  end

  # Authentication
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  root 'welcome#index'
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :sprint, optional: true
  belongs_to :project
  belongs_to :user, optional: true

  has_many :issue_comments
  has_many :work_entries

  enum issue_type: [ :bug, :feature, :task ]
  enum state: [ :todo, :in_progress, :to_test, :testing, :done ]

  audited
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update]
  before_action :authorize

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @sprint = params[:sprint]
    @project = Project.find(params[:project_id])
  end

  # GET /issues/new
  def new
    @issue = Issue.new
    @issue.project = Project.find(params[:project_id])
  end

  # GET /issues/1/edit
  def edit
    @project = Project.find(params[:project_id])
  end

  # POST /issues
  # POST /issues.json
  def create
    ip = issue_params
    ip[:state] = ip[:state].to_i
    ip[:issue_type] = ip[:issue_type].to_i
    @issue = Issue.new(ip)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to project_issue_path(@issue.project, @issue), notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      ip = issue_params
      ip[:state] = ip[:state].to_i
      ip[:issue_type] = ip[:issue_type].to_i
      if @issue.update(ip)
        format.html { redirect_to project_issue_path(@issue.project, @issue), notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:name, :description, :estimation, :issue_type, :state, :sprint_id, :project_id, :user_id)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def issue_type_options
    [['BUG', 0], ['FEATURE', 1], ['TASK', 2]]
  end

  def issue_state_options
    [['TODO', 0], ['In Progress', 1], ['To Test', 2], ['Testing', 3], ['Done', 4]]
  end

  def resolve_issue_type_id(issue_type)
    map = { bug: 0, feature: 1, task: 2 }
    map[issue_type.to_sym]
  end

  def resolve_issue_state_id(issue_state)
    map = { todo: 0, in_progress: 1, to_test: 2, testing: 3, done: 4 }
    map[issue_state.to_sym]
  end

  def get_issues(project, sprint_id)
    return project.issues if sprint_id.nil?
    project.sprints.select { |s| sprint_id.to_i == s.id }.first.issues
  end

end

app/views/issues/_form.html.erb
<%= form_with(model: issue, url: project_issues_path, local: true) do |form| %>
    <% if issue.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

          <ul>
            <% issue.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :issue_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, id: :issue_description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :estimation %>
      <div class="input-group">
        <%= form.number_field :estimation, id: :issue_estimation, class: 'form-control', 'aria-describedby' => 'basic-addon2' %>
        <span class="input-group-addon" id="basic-addon2">hours</span>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :project_id %>
      <%= form.select(:project_id,
                      options_for_select(Project.order(:name).map {| e |[e[:name], e[:id]]  }, :selected => issue.project.id),
                      {},
                      class: 'form-control',
                      id: :issue_project_id) %>
    </div>

    <div class="form-group">
      <%= form.label :user_id, 'Assignee' %>
      <%= form.select(:user_id,
                      options_for_select(User.order(:name).map {| e |[e[:name], e[:id]]  }),
                      {},
                      class: 'form-control',
                      id: :issue_user_id) %>
    </div>

    <div class="form-group">
      <%= form.label :sprint_id %>
      <%= form.select(:sprint_id,
                      options_for_select(Sprint.where(project_id: issue.project.id).map {| e |[e[:name], e[:id]]  }),
                      {},
                      class: 'form-control',
                      id: :issue_sprint_id) %>
    </div>


    <div class="form-group">
      <%= form.label :state %>
      <%= form.select(:state, issue_state_options, {}, { :id => 'issue_state', :class => 'form-control' }) %>
    </div>

    <div class="form-group">
      <%= form.label :issue_type %>
      <%= form.select(:issue_type, issue_type_options, {}, { :id => 'issue_issue_type', :class => 'form-control' }) %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', project_path(issue.project), class: 'btn btn-default' %>
    </div>
<% end %>

<script>
    $(document).ready(function () {
        $("#issue_state").select2({theme: 'bootstrap'});
        $("#issue_issue_type").select2({theme: 'bootstrap'});
        $("#issue_user_id").select2({theme: 'bootstrap'});
        $("#issue_sprint_id").select2({theme: 'bootstrap'});
        $("#issue_project_id").select2({theme: 'bootstrap'});
    });
</script>

app/views/issues/_form_edit.html.erb
<%= form_with(model: issue, url: project_issue_path, local: true) do |form| %>
    <% if issue.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

          <ul>
            <% issue.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :issue_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, id: :issue_description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :estimation %>
      <div class="input-group">
        <%= form.number_field :estimation, id: :issue_estimation, class: 'form-control', 'aria-describedby' => 'basic-addon2' %>
        <span class="input-group-addon" id="basic-addon2">hours</span>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :project_id %>
      <%= form.select(:project_id,
                      options_for_select(Project.order(:name).map {| e |[e[:name], e[:id]]  }, :selected => issue.project.id),
                      {},
                      class: 'form-control',
                      id: :issue_project_id) %>
    </div>

    <div class="form-group">
      <%= form.label :user_id %>
      <%= form.select(:user_id,
                      options_for_select(User.order(:name).map {| e |[e[:name], e[:id]]  }),
                      {},
                      class: 'form-control',
                      id: :issue_user_id) %>
    </div>

    <div class="form-group">
      <%= form.label :sprint_id %>
      <%= form.select(:sprint_id,
                      options_for_select(Sprint.where(project_id: issue.project.id).map {| e |[e[:name], e[:id]]  }),
                      {},
                      class: 'form-control',
                      id: :issue_sprint_id) %>
    </div>


    <div class="form-group">
      <%= form.label :state %>
      <%= form.select(:state,
                      issue_state_options,
                      { selected: resolve_issue_state_id(issue.state) },
                      {:id => 'issue_state', :class => 'form-control' })
      %>
    </div>

    <div class="form-group">
      <%= form.label :issue_type %>
      <%= form.select(:issue_type,
                      issue_type_options,
                      { selected: resolve_issue_type_id(issue.issue_type) },
                      class: 'form-control',
                      id: :issue_issue_type)
      %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', project_issue_path(issue.project, issue), class: 'btn btn-default' %>
    </div>
<% end %>

<script>
    $(document).ready(function () {
        $("#issue_state").select2({theme: 'bootstrap'});
        $("#issue_issue_type").select2({theme: 'bootstrap'});
        $("#issue_user_id").select2({theme: 'bootstrap'});
        $("#issue_sprint_id").select2({theme: 'bootstrap'});
        $("#issue_project_id").select2({theme: 'bootstrap'});
    });
</script>

app/views/issues/edit.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.role == :admin.to_s %>
          <li><%= link_to 'Project management', projects_path %></li>
          <li><%= link_to 'Team management', teams_path %></li>
          <li><%= link_to 'User management', users_path %></li>
      <% end  %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log out', '/logout' %></li>
        </ul>
      </li>
    </ul>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Editing Issue - <%= @issue.name %></h1>
    <div class="well">
      <%= render 'form_edit', issue: @issue %>
    </div>
  </div>
</div>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Estimation</th>
      <th>Type</th>
      <th>State</th>
      <th>Sprint</th>
      <th>Project</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.name %></td>
        <td><%= issue.description %></td>
        <td><%= issue.estimation %></td>
        <td><%= issue.type %></td>
        <td><%= issue.state %></td>
        <td><%= issue.sprint %></td>
        <td><%= issue.project %></td>
        <td><%= issue.user %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.role == :admin.to_s %>
          <li><%= link_to 'Project management', projects_path %></li>
          <li><%= link_to 'Team management', teams_path %></li>
          <li><%= link_to 'User management', users_path %></li>
      <% end  %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log out', '/logout' %></li>
        </ul>
      </li>
    </ul>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">New Issue</h1>
    <div class="well">
      <%= render 'form', issue: @issue %>
    </div>
  </div>
</div>

app/views/issues/show.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.role == :admin.to_s %>
          <li><%= link_to 'Project management', projects_path %></li>
          <li><%= link_to 'Team management', teams_path %></li>
          <li><%= link_to 'User management', users_path %></li>
      <% end  %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log out', '/logout' %></li>
        </ul>
      </li>
    </ul>
<% end %>

<div class="col-md-12">
  <%= link_to 'New issue', new_project_issue_path(@project), class: 'btn btn-success pull-right' %>
  <h1 class="text-center"><%= @project.name %></h1>
  <br>
</div>
<div class="col-md-12">
  <div class="col-md-4">
    <div>
      <h3>Issues</h3>
      <div class="list-group">
        <% get_issues(@project, @sprint).each do |issue| %>
            <%= link_to project_issue_path(@project, issue, sprint: @sprint), class: 'list-group-item'.concat(@issue.id == issue.id ? ' active' : '') do %>
                <h4 class="list-group-item-heading">
                  <%= issue.name %></h4>
                <p class="list-group-item-text">
                  <%= issue.description %></p>
            <% end %>
        <% end %>
      </div>
    </div>
    <div>
      <h3>Sprints</h3><%= link_to 'clear', project_path(@project) %>
      <div class="list-group">
        <% @project.sprints.each do |sprint| %>
            <%= link_to sprint.name, project_path(@project, sprint: sprint), class: 'list-group-item'.concat(@sprint.to_i == sprint.id ? ' active' : '') %>
        <% end %>
      </div>

    </div>
  </div>
  <div class="col-md-8">
    <div class="well">
      <%= link_to 'Edit', edit_project_issue_path(@project, @issue), class: 'btn btn-primary pull-right' %>
      <h2><%= @issue.issue_type.to_s.upcase + ': ' + @issue.name %></h2>
      <hr>

      <p class="lead">Description:</p>
      <p><%= @issue.description %></p>

      <p class="h4 pull-right">Status: <%= @issue.state.to_s.upcase %></p>

      <p class="h4">Estimation:</p>
      <p><%= @issue.estimation %> hours</p>

    </div>
    <div class="row">
      <div class="col-md-12">
        <ul class="nav nav-tabs">
          <li class="active"><a data-toggle="tab" href="#comments">Comments</a></li>
          <li><a data-toggle="tab" href="#work_log">Work log</a></li>
          <li><a data-toggle="tab" href="#changes">Changes</a></li>
        </ul>

        <div class="tab-content">
          <div id="comments" class="tab-pane fade in active">
            <br>
            <% @issue.issue_comments.each do |c| %>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title"><%= c.user.name %> (<%= c.created_at %>)</h3>
                  </div>
                  <div class="panel-body">
                    <p><%= c.comment  %></p>
                  </div>
                </div>
            <% end %>
            <%= render 'issue_comments/form', issue_comment: IssueComment.new(issue: @issue, user_id: current_user.id) %>
          </div>
          <div id="work_log" class="tab-pane fade">
            <br>
            <% @issue.work_entries.each do |we| %>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title"><%= we.user.name %> (<%= we.created_at %>)</h3>
                  </div>
                  <div class="panel-body">
                    <p>Spent <%= we.hours %> hours</p>
                  </div>
                </div>
            <% end %>
            <%= render 'work_entries/form', work_entry: WorkEntry.new(issue: @issue, user_id: current_user.id) %>
          </div>
          <div id="changes" class="tab-pane fade">
            <br>
            <% @issue.audits.each do |audit| %>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">Action: <%= audit.action.capitalize %> (<%= audit.created_at %>)</h3>
                  </div>
                  <div class="panel-body">
                    <p><strong>Changes:</strong></p>
                    <% audit.audited_changes.each do |param, value| %>
                        <p><%= param %> => <%= value || 'undefined' %></p>
                    <% end %>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>