config/routes.rb
Rails.application.routes.draw do
  resources :issue_comments
  resources :work_entries
  resources :users
  resources :teams

  resources :sprints do
    resources :issues
  end
  resources :projects do
    resources :issues
  end

  # Authentication
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :teams
  has_many :issues
  validates_presence_of :password_digest, on: :create

  enum role: %i[admin worker]

  has_secure_password
  audited
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:index, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    up = user_params
    up[:role] = 1
    @user = User.new(up)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    up = user_params
    up[:role] = up[:role].to_i
    if @user.update(up)
      redirect_to root_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html {redirect_to users_url, notice: 'User was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    user_params = params.require(:user).permit(:name, :email, :role, :password, :password_confirmation) # don't permit `password_digest` here, that database column should not be allowed to be set by the user!

    # Remove the password and password confirmation keys for empty values
    user_params.delete(:password) unless user_params[:password].present?
    user_params.delete(:password_confirmation) unless user_params[:password_confirmation].present?

    user_params
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_role_options
    [['Admin', 0], ['Worker', 1]]
  end

  def resolve_user_role_id(user_role)
    map = { admin: 0, worker: 1 }
    map[user_role.to_sym]
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :user_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, id: :user_email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, id: :user_password, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, id: :user_password_confirmation, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit 'Sing up', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :user_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, id: :user_email, class: 'form-control' %>
    </div>

    <% if current_user.role == :admin.to_s %>
        <div class="form-group">
          <%= form.label :role %>
          <%= form.select(:role,
                          user_role_options,
                          { selected: resolve_user_role_id(user.role) },
                          {:id => 'user_role', :class => 'form-control' })
          %>
        </div>
        <script>
            $(document).ready(function () {
                $("#user_role").select2({theme: 'bootstrap'});
            });
        </script>

    <% else %>
        <%= form.hidden_field :role, id: :user_role_id %>
    <% end %>
    <%= form.hidden_field :password_digest, id: :user_password_digest %>


    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', root_path, class: 'btn btn-default' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.role == :admin.to_s %>
          <li><%= link_to 'Project management', projects_path %></li>
          <li><%= link_to 'Team management', teams_path %></li>
          <li><%= link_to 'User management', users_path %></li>
      <% end  %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log out', '/logout' %></li>
        </ul>
      </li>
    </ul>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Update profile</h1>
    <div class="well">
      <%= render 'form_edit', user: @user %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'New User', new_user_path, class: 'btn btn-success' %>
  </div>
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.role %></td>
            <td>
              <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-xs btn-default' %>
              <%= link_to 'Destroy', user, class: 'btn btn-xs btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Log in', '/login' %></li>
    </ul>
<% end %>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Sign up</h1>
    <div class="well">
      <%= render 'form', user: @user %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Team:</strong>
  <%= @user.team %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>