config/routes.rb
Rails.application.routes.draw do
  resources :issue_comments
  resources :work_entries
  resources :users
  resources :teams

  resources :sprints do
    resources :issues
  end
  resources :projects do
    resources :issues
  end

  # Authentication
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  root 'welcome#index'
end

app/models/sprint.rb
class Sprint < ApplicationRecord
  belongs_to :project
  has_many :issues

  audited
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  before_action :set_sprint, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  before_action :authorize_admin, only: [:edit, :update, :destroy]

  # GET /sprints
  # GET /sprints.json
  def index
    @sprints = Sprint.all
  end

  # GET /sprints/1
  # GET /sprints/1.json
  def show
  end

  # GET /sprints/new
  def new
    @sprint = Sprint.new
  end

  # GET /sprints/1/edit
  def edit
  end

  # POST /sprints
  # POST /sprints.json
  def create
    @sprint = Sprint.new(sprint_params)

    respond_to do |format|
      if @sprint.save
        format.html { redirect_to sprints_url, notice: 'Sprint was successfully created.' }
        format.json { render :show, status: :created, location: @sprint }
      else
        format.html { render :new }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sprints/1
  # PATCH/PUT /sprints/1.json
  def update
    respond_to do |format|
      if @sprint.update(sprint_params)
        format.html { redirect_to sprints_url, notice: 'Sprint was successfully updated.' }
        format.json { render :show, status: :ok, location: @sprint }
      else
        format.html { render :edit }
        format.json { render json: @sprint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sprints/1
  # DELETE /sprints/1.json
  def destroy
    @sprint.destroy
    respond_to do |format|
      format.html { redirect_to sprints_url, notice: 'Sprint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sprint
      @sprint = Sprint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sprint_params
      params.require(:sprint).permit(:from, :to, :name, :project_id)
    end
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/sprints/_form.html.erb
<%= form_with(model: sprint, local: true) do |form| %>
    <% if sprint.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(sprint.errors.count, "error") %> prohibited this sprint from being saved:</h2>

          <ul>
            <% sprint.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :sprint_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :from %>
      <%= form.text_field :from, id: :sprint_from, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :to %>
      <%= form.text_field :to, id: :to, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :project_id %>
      <%= form.collection_select :project_id, Project.order(:name), :id, :name, {:selected => sprint.project_id, :include_blank => false}, {id: 'sprint_project_id', class: 'form-control'} %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', sprints_path, class: 'btn btn-default' %>
    </div>
<% end %>

<script>
    $(document).ready(function () {
        $("#sprint_project_id").select2({theme: 'bootstrap'});
    });
</script>

app/views/sprints/edit.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.role == :admin.to_s %>
          <li><%= link_to 'Project management', projects_path %></li>
          <li><%= link_to 'Team management', teams_path %></li>
          <li><%= link_to 'User management', users_path %></li>
      <% end  %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log out', '/logout' %></li>
        </ul>
      </li>
    </ul>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Editing Sprint</h1>
    <div class="well">
      <%= render 'form', sprint: @sprint %>
    </div>
  </div>
</div>

app/views/sprints/index.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.role == :admin.to_s %>
          <li><%= link_to 'Project management', projects_path %></li>
          <li><%= link_to 'Team management', teams_path %></li>
          <li><%= link_to 'User management', users_path %></li>
      <% end  %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log out', '/logout' %></li>
        </ul>
      </li>
    </ul>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Sprints</h1>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'New Sprint', new_sprint_path, class: 'btn btn-success' %>
  </div>
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Start</th>
        <th>End</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @sprints.each do |sprint| %>
          <tr>
            <td><%= sprint.name %></td>
            <td><%= sprint.from %></td>
            <td><%= sprint.to %></td>
            <td>
              <%= link_to 'Edit', edit_sprint_path(sprint), class: 'btn btn-xs btn-default' %>
              <%= link_to 'Destroy', sprint, class: 'btn btn-xs btn-danger', method: :delete, data: {confirm: 'Are you sure?' } %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/sprints/new.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.role == :admin.to_s %>
          <li><%= link_to 'Project management', projects_path %></li>
          <li><%= link_to 'Team management', teams_path %></li>
          <li><%= link_to 'User management', users_path %></li>
      <% end  %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log out', '/logout' %></li>
        </ul>
      </li>
    </ul>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">New Sprint</h1>
    <div class="well">
      <%= render 'form', sprint: @sprint %>
    </div>
  </div>
</div>

app/views/sprints/show.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.role == :admin.to_s %>
          <li><%= link_to 'Project management', projects_path %></li>
          <li><%= link_to 'Team management', teams_path %></li>
          <li><%= link_to 'User management', users_path %></li>
      <% end  %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log out', '/logout' %></li>
        </ul>
      </li>
    </ul>
<% end %>


<div class="col-md-12">
  <%= link_to 'New issue', new_project_issue_path(@sprint.project), class: 'btn btn-success pull-right' %>
  <h1 class="text-center"><%= @sprint.project.name %></h1>
  <br>
</div>
<div class="col-md-12">
  <div class="col-md-4">
    <div>
      <h3>Issues</h3>
      <div class="list-group">
        <% @sprint.project.issues.each do |issue| %>
            <%= link_to project_issue_path(@sprint.project, issue), class: 'list-group-item' do %>
                <h4 class="list-group-item-heading">
                  <%= issue.name %></h4>
                <p class="list-group-item-text">
                  <%= issue.description %></p>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="well">
      <h2>Please select an issue</h2>

    </div>
  </div>
</div>