config/routes.rb
Rails.application.routes.draw do
  resources :issue_comments
  resources :work_entries
  resources :users
  resources :teams

  resources :sprints do
    resources :issues
  end
  resources :projects do
    resources :issues
  end

  # Authentication
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  root 'welcome#index'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :team, optional: true
  has_many :sprints
  has_many :issues

  enum status: [ :active, :inactive, :postponed ]

  audited
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  before_action :authorize_admin, only: [:edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @sprint = params[:sprint]
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    pp = project_params
    pp[:status] = pp[:status].to_i
    @project = Project.new(pp)

    respond_to do |format|
      if @project.save
        format.html {redirect_to projects_url, notice: 'Project was successfully created.'}
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      pp = project_params
      pp[:status] = pp[:status].to_i
      if @project.update(pp)
        format.html {redirect_to projects_url, notice: 'Project was successfully updated.'}
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :status, :team_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def get_issues(project, sprint_id)
    return project.issues if sprint_id.nil?
    project.sprints.select { |s| sprint_id.to_i == s.id }.first.issues
  end

  def project_status_options
    [['Active', 0], ['Inactive', 1], ['Postponed', 2]]
  end

  def resolve_project_status_id(status)
    return 0 if status.nil?
    map = { acitve: 0, inactive: 1, postponed: 2 }
    map[status.to_sym]
  end
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
    <% if project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :project_name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, id: :project_description, class: 'form-control' %>
    </div>


    <div class="form-group">
      <%= form.label :status %>
      <%= form.select(:status,
                      project_status_options,
                      { selected: resolve_project_status_id(project.status) },
                      class: 'form-control',
                      id: :project_status)
      %>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', projects_path, class: 'btn btn-default' %>
    </div>
<% end %>

<script>
    $(document).ready(function() { $("#project_status").select2({ theme: 'bootstrap' }); });
</script>

app/views/projects/edit.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.role == :admin.to_s %>
          <li><%= link_to 'Project management', projects_path %></li>
          <li><%= link_to 'Team management', teams_path %></li>
          <li><%= link_to 'User management', users_path %></li>
      <% end  %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log out', '/logout' %></li>
        </ul>
      </li>
    </ul>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Editing Project</h1>
    <div class="well">
      <%= render 'form', project: @project %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.role == :admin.to_s %>
          <li><%= link_to 'Project management', projects_path %></li>
          <li><%= link_to 'Team management', teams_path %></li>
          <li><%= link_to 'User management', users_path %></li>
      <% end  %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log out', '/logout' %></li>
        </ul>
      </li>
    </ul>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'New Project', new_project_path, class: 'btn btn-success' %>
  </div>
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Status</th>
        <th>Team</th>
        <th>Actions</th>
      </tr>
      </thead>

      <tbody>
      <% @projects.each do |project| %>
          <tr>
            <td><%= project.name %></td>
            <td><%= project.description %></td>
            <td><%= project.status %></td>
            <td><%= project.team.nil? ? '' : project.team.name %></td>
            <td>
              <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-xs btn-default' %>
              <%= link_to 'Destroy', project, class: 'btn btn-xs btn-danger', method: :delete, data: {confirm: 'Are you sure?' } %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.role == :admin.to_s %>
          <li><%= link_to 'Project management', projects_path %></li>
          <li><%= link_to 'Team management', teams_path %></li>
          <li><%= link_to 'User management', users_path %></li>
      <% end  %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log out', '/logout' %></li>
        </ul>
      </li>
    </ul>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">New Project</h1>
    <div class="well">
      <%= render 'form', project: @project %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% content_for :navigation do %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.role == :admin.to_s %>
          <li><%= link_to 'Project management', projects_path %></li>
          <li><%= link_to 'Team management', teams_path %></li>
          <li><%= link_to 'User management', users_path %></li>
      <% end  %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Update profile', edit_user_path(current_user) %></li>
          <li><%= link_to 'Log out', '/logout' %></li>
        </ul>
      </li>
    </ul>
<% end %>


<div class="col-md-12">
  <%= link_to 'New issue', new_project_issue_path(@project), class: 'btn btn-success pull-right' %>
  <h1 class="text-center"><%= @project.name %></h1>
  <br>
</div>
<div class="col-md-12">
  <div class="col-md-4">
    <div>
      <h3>Issues</h3>
      <div class="list-group">
        <% get_issues(@project, @sprint).each do |issue| %>
            <%= link_to project_issue_path(@project, issue, sprint: @sprint), class: 'list-group-item' do %>
                <h4 class="list-group-item-heading">
                  <%= issue.name %></h4>
                <p class="list-group-item-text">
                  <%= issue.description %></p>
            <% end %>
        <% end %>
      </div>
    </div>
    <div>
      <h3>Sprints</h3><%= link_to 'clear', project_path(@project) %>
      <div class="list-group">
        <% @project.sprints.each do |sprint| %>
            <%= link_to sprint.name, project_path(@project, sprint: sprint), class: 'list-group-item'.concat(@sprint.to_i == sprint.id ? ' active' : '') %>
        <% end %>
      </div>

    </div>
  </div>
  <div class="col-md-8">
    <div class="well">
      <h2>Please select an issue</h2>
    </div>
  </div>
</div>